package snapshot

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/akash202k/ctx/internal/walker"
)

// FilterRule specifies files/directories to include or exclude.
type FilterRule struct {
	Type string `json:"type"` // "include" or "exclude"
	Path string `json:"path"`
}

// Result contains the generated snapshot and metadata.
type Result struct {
	Content       string              // Full @@CTX format output
	IgnoredFiles  map[string][]string // Path → reasons
	TokenEstimate int                 // Rough estimate (len/4)
}

// Generate creates a ctx snapshot of the repository at basePath.
// filterRules determine which files to include/exclude.
func Generate(basePath string, filterRules []FilterRule) (*Result, error) {
	// Walk the directory tree
	walkResult, err := walker.Walk(basePath)
	if err != nil {
		return nil, fmt.Errorf("walk: %w", err)
	}

	// Apply filter rules
	filteredFiles, ignoredByFilter := applyFilters(walkResult.Files, filterRules, basePath)

	// Merge ignored files from walker and filter
	ignoredFiles := make(map[string][]string)
	for _, skipped := range walkResult.Skipped {
		ignoredFiles[skipped] = []string{"ignored by .gitignore or binary"}
	}
	for path, reasons := range ignoredByFilter {
		ignoredFiles[path] = reasons
	}

	// Build the output
	var sb strings.Builder

	// Header
	sb.WriteString("# CTX_GENERATED_FILE\n\n")

	// META-INFO
	sb.WriteString("@@CTX<META-INFO>\n")
	sb.WriteString("ABOUT_CTX_FILE: This file was generated by ctx - a tool for copying parts of a repository including path and other metadata in a format friendly to provide LLMs.\n")
	sb.WriteString(fmt.Sprintf("BASE_PATH: %s\n", basePath))
	sb.WriteString(fmt.Sprintf("FILTER_RULES: %s\n", formatFilterRules(filterRules)))
	sb.WriteString("STRUCTURE:\n")
	sb.WriteString(buildTree(filteredFiles, basePath))
	sb.WriteString("@@CTX</META-INFO>\n\n")

	// File blocks
	for _, file := range filteredFiles {
		sb.WriteString(fmt.Sprintf("@@CTX<FILE path=%q>\n", file.RelPath))
		sb.WriteString(file.Content)
		if !strings.HasSuffix(file.Content, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString("@@CTX</FILE>\n\n")
	}

	content := sb.String()
	tokenEstimate := len(content) / 4

	return &Result{
		Content:       content,
		IgnoredFiles:  ignoredFiles,
		TokenEstimate: tokenEstimate,
	}, nil
}

func applyFilters(files []walker.FileEntry, rules []FilterRule, basePath string) ([]walker.FileEntry, map[string][]string) {
	if len(rules) == 0 {
		// Default: include everything
		return files, nil
	}

	// Sort rules by path length (longest first) for specificity - matches Astrolark behavior
	sortedRules := make([]FilterRule, len(rules))
	copy(sortedRules, rules)
	sort.Slice(sortedRules, func(i, j int) bool {
		return len(sortedRules[i].Path) > len(sortedRules[j].Path)
	})

	included := make(map[string]bool)
	ignored := make(map[string][]string)

	for _, file := range files {
		shouldInclude := true // Default: include when no rule matches (Astrolark defaultInclude: true)

		// First matching rule wins (after sorting by path length)
		for _, rule := range sortedRules {
			matched := false

			if rule.Path == "." {
				// Wildcard matches everything
				matched = true
			} else if file.RelPath == rule.Path {
				// Exact match
				matched = true
			} else if strings.HasPrefix(file.RelPath, rule.Path+string(filepath.Separator)) {
				// Separator-aware prefix matching (e.g., "src" matches "src/main.go" but not "srcfoo/bar.go")
				matched = true
			}

			if matched {
				shouldInclude = (rule.Type == "include")
				break // First match wins
			}
		}

		if shouldInclude {
			included[file.RelPath] = true
		} else {
			ignored[file.RelPath] = []string{"excluded by filter rules"}
		}
	}

	// Build filtered list maintaining order
	var filtered []walker.FileEntry
	for _, file := range files {
		if included[file.RelPath] {
			filtered = append(filtered, file)
		}
	}

	return filtered, ignored
}

func formatFilterRules(rules []FilterRule) string {
	if len(rules) == 0 {
		return `[{"type":"include","path":"."}]`
	}

	parts := make([]string, len(rules))
	for i, rule := range rules {
		parts[i] = fmt.Sprintf(`{"type":%q,"path":%q}`, rule.Type, rule.Path)
	}
	return "[" + strings.Join(parts, ",") + "]"
}

// treeNode represents a node in the directory tree structure
type treeNode struct {
	name     string
	isDir    bool
	children map[string]*treeNode
}

func buildTree(files []walker.FileEntry, basePath string) string {
	root := &treeNode{children: make(map[string]*treeNode)}

	for _, file := range files {
		parts := strings.Split(file.RelPath, string(filepath.Separator))
		current := root

		for i, part := range parts {
			if current.children == nil {
				current.children = make(map[string]*treeNode)
			}
			if _, exists := current.children[part]; !exists {
				current.children[part] = &treeNode{
					name:     part,
					isDir:    i < len(parts)-1,
					children: make(map[string]*treeNode),
				}
			}
			current = current.children[part]
		}
	}

	var sb strings.Builder
	var printNode func(*treeNode, string, bool)
	printNode = func(n *treeNode, prefix string, isLast bool) {
		for i, name := range sortedKeys(n.children) {
			child := n.children[name]
			isLastChild := i == len(n.children)-1

			sb.WriteString(prefix)
			if isLastChild {
				sb.WriteString("└─ ")
			} else {
				sb.WriteString("├─ ")
			}
			sb.WriteString(name)
			sb.WriteString("\n")

			if child.isDir && len(child.children) > 0 {
				newPrefix := prefix
				if isLastChild {
					newPrefix += "   "
				} else {
					newPrefix += "│  "
				}
				printNode(child, newPrefix, isLastChild)
			}
		}
	}

	printNode(root, "", true)
	return sb.String()
}

func sortedKeys(m map[string]*treeNode) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	// Simple sort - directories first, then alphabetically
	// For simplicity, just alphabetical here
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}
